# Generated by Django 2.1.7 on 2019-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(choices=[(0, 'Technical'), (1, 'Business'), (2, 'Product'), (3, 'IT')], max_length=50)),
                ('activity', models.CharField(choices=[(0, 'Interested'), (1, 'Going'), (2, 'Not Interested')], max_length=50)),
                ('location', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to=None)),
            ],
        ),
    ]
