# Generated by Django 2.1.7 on 2019-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190213_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.IntegerField(choices=[(0, 'Interested'), (1, 'Going'), (2, 'Not Interested')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.IntegerField(choices=[(0, 'Technical'), (1, 'Business'), (2, 'Product'), (3, 'IT')]),
        ),
    ]
