# Generated by Django 2.1.7 on 2019-02-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
        ('events', '0004_auto_20190213_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='startups.Startup'),
        ),
    ]
