# Generated by Django 2.1.7 on 2019-02-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.IntegerField(choices=[(0, 'Meeting'), (1, 'Conference'), (2, 'Seminar'), (3, 'Hackathon')]),
        ),
    ]
