# Generated by Django 2.1.7 on 2019-02-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190215_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='activity',
        ),
    ]
