# Generated by Django 2.1.7 on 2019-02-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190216_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='images/events/codergirl.png', null=True, upload_to='images/events/'),
        ),
    ]
