# Generated by Django 2.1.7 on 2019-02-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20190214_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_seats', to='rooms.Room'),
        ),
    ]
