# Generated by Django 2.1.7 on 2019-02-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20190215_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
