# Generated by Django 2.1.7 on 2019-02-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('motto', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Startup')),
                ('worth', models.IntegerField()),
            ],
        ),
    ]
