# Generated by Django 2.1.7 on 2019-02-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('update_title', models.CharField(max_length=50)),
                ('update_description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=None)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='startups.Startup')),
            ],
        ),
    ]
