# Generated by Django 2.1.7 on 2019-02-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='startup',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='startup',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='startup',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
