# Generated by Django 2.1.7 on 2019-02-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_auto_20190216_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(default='images/startups/logo/bg.jpg', upload_to='images/startups/logo/'),
        ),
    ]
