# Generated by Django 2.1.7 on 2019-02-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_auto_20190216_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(default='images/startups/logo/bg.png', upload_to='images/startups/logo/'),
        ),
    ]
