# Generated by Django 2.1.7 on 2019-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_auto_20190216_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'REJECTED')], default=0),
        ),
    ]
