# Generated by Django 2.1.7 on 2019-02-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_startup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(default='images/startups/logo/logo.png', upload_to='images/startups/logo/'),
        ),
    ]
