# Generated by Django 2.1.7 on 2019-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_auto_20190216_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='startuplog',
            name='sentiment',
            field=models.IntegerField(default=0),
        ),
    ]
