# Generated by Django 2.1.7 on 2019-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0009_mentoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='email',
            field=models.CharField(default='root@gmail.com', max_length=50),
        ),
    ]
