# Generated by Django 2.1.7 on 2019-02-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_coffeelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='extra_coffee',
        ),
        migrations.AddField(
            model_name='coffee',
            name='total_coffee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='free_coffee',
            field=models.IntegerField(default=5),
        ),
    ]
