# Generated by Django 2.1.7 on 2019-02-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190215_1530'),
        ('accounts', '0011_auto_20190215_1214'),
    ]

    operations = [
    ]
