# Generated by Django 2.1.7 on 2019-02-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20190215_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='amount_due',
            field=models.IntegerField(default=0),
        ),
    ]
