# Generated by Django 2.1.7 on 2019-02-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=1000),
        ),
    ]
