# Generated by Django 2.1.7 on 2019-02-16 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.TextField(unique=True)),
                ('room_type', models.IntegerField(choices=[(0, 'Meeting'), (1, 'Office'), (2, 'Conference')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.TextField(unique=True)),
                ('booked', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_alloted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('request_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('request_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='seats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_room', to='RoomManagement.Seat'),
        ),
    ]
