# Generated by Django 2.1.7 on 2019-02-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManagement', '0003_auto_20190216_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatrequest',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
