# Generated by Django 2.1.7 on 2019-02-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManagement', '0005_seatrequest_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrequest',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='RoomManagement.Seat'),
        ),
    ]
