# Generated by Django 2.1.7 on 2019-02-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManagement', '0006_auto_20190216_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
