# Generated by Django 2.1.7 on 2019-02-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManagement', '0007_seat_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatrequest',
            name='date',
        ),
    ]
