# Generated by Django 2.1.7 on 2019-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManagement', '0008_remove_seatrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatrequest',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
