# Generated by Django 2.1.7 on 2019-02-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManagement', '0009_seatrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatrequest',
            name='request_from',
        ),
        migrations.RemoveField(
            model_name='seatrequest',
            name='request_to',
        ),
        migrations.RemoveField(
            model_name='seatrequest',
            name='seat',
        ),
    ]
