# Generated by Django 2.1.7 on 2019-02-16 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManagement', '0011_auto_20190216_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrequest',
            name='request_from',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seatrequest',
            name='request_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seatrequest',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='RoomManagement.Seat'),
        ),
    ]
