# Generated by Django 2.1.7 on 2019-02-16 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManagement', '0013_auto_20190216_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_alloted', to=settings.AUTH_USER_MODEL),
        ),
    ]
